### PR TITLE
README: add Example Interaction section

### PR DESCRIPTION
**Pull request by eugulixes**
To replace an obsolete and removed one.

### CODE REVIEW

**Review by sibiryoff — APPROVED** [review]

**Review by TheSergeX — COMMENTED** [review]
I think we can add to example everything commands such as `birthdays on` and `birthday delete`

**Comment by eugulixes** [comment]
@Sergei-vb, I guess it will be a bit redundant. @ukhryab, what do you think?

**Comment by sibiryoff** [comment]
@eugulixes I agree with you, because it's not a full help page, but just a sample.

**Comment by sibiryoff** [comment]
Maybe, we should provide full list of available commands somewhere.

**Pull request merged**
